# Generated by Django 2.0.6 on 2018-10-24 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('django_jwtauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remoteuser',
            old_name='sub',
            new_name='claim_identifier',
        ),
    ]
